#!/bin/bash -e

# Called from install_update.sh with arguments
# /path/to/script /path/to/new/rootfs [flag1 [flag2 ...]]
#
# This script may run in Busybox initramfs environment,
# so if you need some special tools or features, use ones from rootfs.
#
# /dev, /proc and /sys are already bind-mounted
# from host system to rootfs tree.

if [ $# -lt 1 ]; then
    echo "Usage: $0 path/to/rootfs [flag1 [flag2 ...]]"
    exit 2
fi

ROOTFS="$1"
shift
FLAGS="$*"

flag_set() {
	echo "$FLAGS" | grep -- "--$1" >/dev/null 2>&1
}

if ! flag_set "factoryreset" ; then
    echo "Skipping WBEC firmware update (use factory reset to do it)"
    exit
fi

FDT_NAME=$(chroot "$ROOTFS" /usr/lib/wb-utils/device-factory-fdt.sh)
FACTORY_DTB="/boot/dtbs/$FDT_NAME.dtb"

if [ ! -f "$ROOTFS/$FACTORY_DTB" ]; then
    echo "Cannot find factory DTB $FACTORY_DTB"
    exit 1
fi

# extracting compatible property from factory DTB
COMPATIBLE=$(chroot "$ROOTFS" fdtget -t s "$FACTORY_DTB" / compatible)

case "$COMPATIBLE" in
    *wirenboard,wirenboard-74x*)
        if ! ls "$ROOTFS/dev/i2c*" >/dev/null 2>&1; then
            mount -t bind /dev "$ROOTFS/dev"
            trap 'umount $ROOTFS/dev' EXIT
        fi

        echo "Trying to update WBEC firmware"
        "$ROOTFS/chroot_this.sh" /bin/bash -c "export DTB=$FACTORY_DTB; /usr/bin/wb-ec-firmware-update"
        ;;
    *)
        echo "This Wiren Board does not have WBEC, exiting"
        ;;
esac
