#!/bin/sh -e

# Called from install_update.sh with arguments
# /path/to/script /path/to/new/rootfs [flag1 [flag2 ...]]
#
# This script may run in Busybox initramfs environment,
# so if you need some special tools or features, use ones from rootfs.
#
# /dev, /proc and /sys are already bind-mounted
# from host system to rootfs tree.

if [ $# -lt 1 ]; then
    echo "Usage: $0 path/to/rootfs [flag1 [flag2 ...]]"
    exit 2
fi

ROOTFS="$1"
shift
FLAGS="$*"

flag_set() {
    echo "$FLAGS" | grep -- "--$1" >/dev/null 2>&1
}

if ! flag_set "factoryreset" ; then
    echo "Skipping u-boot update (use factory reset to do it)"
    exit
fi

if [ -e "$ROOTFS/usr/bin/u-boot-install-wb" ] ; then
    echo "Trying to install u-boot using u-boot-install-wb from new rootfs"
    chroot "$ROOTFS" /usr/bin/u-boot-install-wb --force
    cp $ROOTFS/etc/fw_env.config /etc/fw_env.config
else
    echo "No u-boot installer found in new rootfs, skipping step"
fi
