#!/bin/sh -e

# Called from install_update.sh with arguments
# /path/to/script /path/to/new/rootfs [flag1 [flag2 ...]]
#
# This script may run in Busybox initramfs environment,
# so if you need some special tools or features, use ones from rootfs.

if [ $# -lt 1 ]; then
    echo "Usage: $0 path/to/rootfs [flag1 [flag2 ...]]"
    exit 2
fi

ROOTFS="$1"
shift
FLAGS="$*"

flag_set() {
	echo "$FLAGS" | grep -- "--$1" >/dev/null 2>&1
}

if ! flag_set "factoryreset" ; then
    echo "Skipping u-boot update (use factory reset to do it)"
    exit
fi

if [ -e "$ROOTFS/usr/bin/u-boot-install-wb" ] ; then
    echo "Trying to install u-boot using u-boot-install-wb from new rootfs"

    CHROOT_MOUNTS=""
    cleanup_mounts() {
        for m in $CHROOT_MOUNTS; do
            umount "$m" || true
        done
    }
    trap cleanup_mounts EXIT

    if [ ! -e "$ROOTFS/dev/null" ] ; then
        echo "Mount /dev to rootfs"
        mount -o bind /dev "$ROOTFS/dev"
        CHROOT_MOUNTS="$CHROOT_MOUNTS $ROOTFS/dev"
    fi

    if [ ! -e "$ROOTFS/proc/device-tree" ] ; then
        echo "Mount /proc to rootfs"
        mount -o bind /proc "$ROOTFS/proc"
        CHROOT_MOUNTS="$CHROOT_MOUNTS $ROOTFS/proc"
    fi

    chroot "$ROOTFS" /usr/bin/u-boot-install-wb --force
else
    echo "No u-boot installer found in new rootfs, skipping step"
fi
