#!/bin/sh -e

# Called from install_update.sh with arguments
# /path/to/script /path/to/new/rootfs [flag1 [flag2 ...]]
#
# This script may run in Busybox initramfs environment,
# so if you need some special tools or features, use ones from rootfs.
#
# /dev, /proc and /sys are already bind-mounted
# from host system to rootfs tree.

if [ $# -lt 1 ]; then
    echo "Usage: $0 path/to/rootfs [flag1 [flag2 ...]]"
    exit 2
fi

ROOTFS="$1"
shift
FLAGS="$*"

flag_set() {
	echo "$FLAGS" | grep -- "--$1" >/dev/null 2>&1
}

DATA_MOUNT=$(mktemp -d)
mount /dev/mmcblk0p6 "$DATA_MOUNT" || {
    echo "Failed to mount /dev/mmcblk0p6 to $DATA_MOUNT"
    exit 1
}

trap 'umount $DATA_MOUNT; rmdir $DATA_MOUNT' EXIT

WB_RESTORE_DIR="$DATA_MOUNT/.wb-restore/.logs"

if flag_set "factoryreset" ; then
    echo "Saving information about this factory reset"
    mkdir -p "$WB_RESTORE_DIR"

    {
        LANG="C" date
        echo "FIT file: $FIT"
        cat "$ROOTFS/etc/wb-fw-version" || true
        cat "$ROOTFS/usr/lib/wb-release" || true
    } > "$WB_RESTORE_DIR/$(date +%s).entry"
fi
