#!/usr/bin/env bash

IFACE=$1
EVENT=$2

NM_LEASESFILE="/var/lib/NetworkManager/dnsmasq-${IFACE}.leases"

# On some systems mac for usb-device could be random
# => manually renewing dhcp leases to avoid addrs overflow on debug-network connecting
# The shared connection lives on the dbgbr bridge (ports: dbg0 RNDIS, dbge0 ECM)
if [[ $IFACE == "dbgbr" ]] && [[ $EVENT == "up" ]] && [[ -f $NM_LEASESFILE ]]
then
    rm "$NM_LEASESFILE"
fi
