#!/bin/sh
set -e

if [ "$1" = "purge" ] ; then
	rm /etc/rc3.d/S01wb-gsm-rtc
	update-rc.d wb-prepare remove >/dev/null
	update-rc.d wb-gsm-rtc remove >/dev/null
	update-rc.d wb-init remove >/dev/null
	update-rc.d wb-watch-update remove >/dev/null
fi

#DEBHELPER#

exit 0
